export enum CaseProgressStatus {
    ONGOING_NOT_STARTING = 'ONGOING_NOT_STARTING',

    ONGOING_ANALYSIS = 'ONGOING_ANALYSIS',

    CUSTOMER_APPOINTEMENT_PROPOSAL = 'CUSTOMER_APPOINTEMENT_PROPOSAL',

    REOPENED = 'REOPENED',

    TREATMENT_END = 'TREATMENT_END',

    INCIDENT_CIBLAGE_CREATED = 'INCIDENT_CIBLAGE_CREATED'
};
