# Default values for fastr-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: production
tag: production

fastr:
  name: fastr-web
  #Nommer le service selon le path qui sera root sur l'ingress (/fastr/{xxxx})

  intranet:
    replicaCount: 3
    ingress:
      enabled: true
      annotations: {}
      hosts:
        - url: fastr-fut.private.sfr.com
          services:
            - intranet
        - url: fastr.web.add.ctn1.pic.services.prod
          services:
            - intranet
        - url: fastr.web.add.ctn0.pic.services.prod
          services:
            - intranet
        - url: fastr.web.add.ctn.pic.services.prod
          services:
            - intranet
  extranet:
    replicaCount: 1
    ingress:
      enabled: true
      annotations: {}
      hosts:
        - url: fastr-fut.espacesfr.sfr.fr
          services:
            - extranet

  internet:
    replicaCount: 1
    ingress:
      enabled: true
      annotations: {}
      hosts:
        - url: fastr-fut.distrib.sfr.fr
          services:
            - internet
