# Default values for fastr-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: integration
tag: integration

fastr:
  name: fastr-web
  #Nommer le service selon le path qui sera root sur l'ingress (/fastr/{xxxx})
  extranet:
    replicaCount: 1
    ingress:
      enabled: true
      annotations: {}
      hosts:
        - url: fastr-integ-pack.espacesfr.sfr.fr
          services:
            - extranet
    resources:
      requests:
        cpu: 50m
        memory: 128Mi


  internet:
    replicaCount: 1
    ingress:
      enabled: true
      annotations: {}
      hosts:
        - url: fastr-integ-pack.distrib.sfr.fr
          services:
            - internet
    resources:
      requests:
        cpu: 50m
        memory: 128Mi

  intranet:
    replicaCount: 1
    ingress:
      enabled: true
      annotations: {}
      hosts:
        - url: fastr-integ.pfv.private.sfr.com
          services:
            - intranet
        - url: fastr-integ.web.ctn1.pic.services.pack
          services:
            - intranet
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
#Ingress de FASTR Backend
#Ajouter les services définis plus haut pour ajouter une règle de routage de type "/fastr-{xxxx}/" vers le service et le port