export interface ActionsType {
    type: string
    // tslint:disable-next-line:no-any
    payload?: any
}

export const TOGGLE_BLOCKING_UI = "TOGGLE_BLOCKING_UI"
export const SET_PROCESSING = "SET_PROCESSING"

// Case Redux Store Actions Types
export const FETCH_CURRENT_CASE = "FETCH_CURRENT_CASE"
export const STORE_CASE = "STORE_CASE"
export const ERROR_FETCHING_CASE = "ERROR_FETCHING_CASE"

export const UPDATE_CASE_START = "UPDATE_CASE_START"
export const UPDATE_CASE_SUCCESS = "UPDATE_CASE_SUCCESS"
export const ERROR_UPDATE_CASE = "ERROR_UPDATE_CASE"

export const ADD_NOTE_CASE_START = "ADD_NOTE_CASE_START"
export const ADD_NOTE_CASE_SUCCESS = "ADD_NOTE_CASE_SUCCESS"
export const ERROR_ADD_NOTE_CASE = "ERROR_ADD_NOTE_CASE"

export const FETCH_CURRENT_CASE_QUALIFICATION = "FETCH_CURRENT_CASE_QUALIFICATION"
export const STORE_CASE_QUALIFICATION = "STORE_CASE_QUALIFICATION"
export const ERROR_FETCHING_CASE_QUALIFICATION = "ERROR_FETCHING_CASE_QUALIFICATION"

export const SHOW_GCO = "SHOW_GCO"
export const HIDE_GCO = "HIDE_GCO"
export const SHOW_SOCO = "SHOW_SOCO"
export const HIDE_SOCO = "HIDE_SOCO"

export const SHOW_REGUL = "SHOW_REGUL"
export const HIDE_REGUL = "HIDE_REGUL"

export const SET_SESSION_USER_ACTIVITY = "SET_SESSION_USER_ACTIVITY"
export const STORE_SESSION = "STORE_SESSION"
export const STORE_AUTHORIZATION = "STORE_AUTHORIZATION"
export const FETCH_AUTHORIZATION = "FETCH_AUTHORIZATION"
export const ERROR_FETCHING_AUTHORIZATIONS = "ERROR_FETCH_AUTHORIZATION"
export const SET_ADG_DONE_BY_BOUCLE_ADG = "SET_ADG_DONE_BY_BOUCLE_ADG"

export const SET_BOUCLE_ADG = "SET_BOUCLE_ADG"
export const SET_SCALING_CONCLUSION_REF = "SET_SCALING_CONCLUSION_REF"
export const UPDATE_CASE_PROGRESS_STATUS = "UPDATE_CASE_PROGRESS_STATUS"
export const SET_DISPLAY_GRID_ADG_FOR_DISRC = "SET_DISPLAY_GRID_ADG_FOR_DISRC"
export const SET_CURRENT_CONTACT_ID = "SET_CURRENT_CONTACT_ID"

// CASE BEHAVIOUR
export const FORM_COMPLETE = "FORM_COMPLETE"
export const FORM_INCOMPLETE = "FORM_INCOMPLETE"
export const SCALING_MODE_ON = "SCALING_MODE_ON"
export const SCALING_MODE_OFF = "SCALING_MODE_OFF"
export const SET_CASE_QUALIFICATION = "SET_CASE_QUALIFICATION"
export const SET_CASE_MOTIF = "SET_CASE_MOTIF"
export const SCALING_ELIGIBILITY_TRUE = "SCALING_ELIGIBILITY_TRUE"
export const SCALING_ELIGIBILITY_FALSE = "SCALING_ELIGIBILITY_FALSE"
export const SET_ADDITIONAL_DATA = "SET_ADDITIONAL_DATA"
export const SET_VALID_ROUTING_RULE = "SET_VALID_ROUTING_RULE"
export const SET_IS_AUTO_ASSIGN = "SET_IS_AUTO_ASSIGN"
export const SET_UPDATE_MODE_FALSE = "SET_UPDATE_MODE_FALSE"
export const SET_UPDATE_MODE_TRUE = "SET_UPDATE_MODE_TRUE"
export const SCALED_ELIGIBILITY_TO_MODIFY_ON = "SCALED_ELIGIBILITY_TO_MODIFY_ON"
export const SCALED_ELIGIBILITY_TO_MODIFY_OFF = "SCALED_ELIGIBILITY_TO_MODIFY_OFF"
export const REVERT_SCALING_TRUE = "REVERT_SCALING_TRUE"
export const REVERT_SCALING_FALSE = "REVERT_SCALING_FALSE"
export const IS_WITH_AUTO_ASSIGN_TRUE = "IS_WITH_AUTO_ASSIGN_TRUE"
export const IS_WITH_AUTO_ASSIGN_FALSE = "IS_WITH_AUTO_ASSIGN_FALSE"
export const IS_FROM_AUTO_ASSIGN_TRUE = "IS_FROM_AUTO_ASSIGN_TRUE"
export const IS_AUTO_ASSIGN_BUTTON_DISABLED_TRUE = "IS_AUTO_ASSIGN_BUTTON_DISABLED_TRUE"
export const IS_AUTO_ASSIGN_BUTTON_DISABLED_FALSE = "IS_AUTO_ASSIGN_BUTTON_DISABLED_FALSE"
export const IS_FORCE_AUTO_ASSIGN_TRUE = "IS_FORCE_AUTO_ASSIGN_TRUE"
export const IS_FORCE_AUTO_ASSIGN_FALSE = "IS_FORCE_AUTO_ASSIGN_FALSE"
export const FORMSY_VALID = "FORMSY_VALID"
export const FORMSY_INVALID = "FORMSY_INVALID"
export const FINISHING_TREATMENT_TRUE = "FINISHING_TREATMENT_TRUE"
export const FINISHING_TREATMENT_FALSE = "FINISHING_TREATMENT_FALSE"
export const SHOW_MODAL_VIEW_CASE = "SHOW_MODAL_VIEW_CASE"
export const HIDE_MODAL_VIEW_CASE = "HIDE_MODAL_VIEW_CASE"
export const SET_IS_ONLY_NOTE_TO_TRUE = "SET_IS_ONLY_NOTE_TO_TRUE"
export const SET_IS_ONLY_NOTE_TO_FALSE = "SET_IS_ONLY_NOTE_TO_FALSE"
export const SET_FORCE_NOTE_TO_TRUE = "SET_FORCE_NOTE_TO_TRUE"
export const SET_FORCE_NOTE_TO_FALSE = "SET_FORCE_NOTE_TO_FALSE"
export const SET_IS_CURRENT_OWNER = "SET_IS_CURRENT_OWNER"
export const SET_IS_UPDATE_ENABLED_TO_TRUE = "SET_IS_UPDATE_ENABLED_TO_TRUE"
export const SET_IS_UPDATE_ENABLED_TO_FALSE = "SET_IS_UPDATE_ENABLED_TO_FALSE"
export const TOGGLE_MODAL_VIEW_CASE = "TOGGLE_MODAL_VIEW_CASE"
export const SET_ADD_CONTACT_FOR_NOTE_TO_TRUE = "SET_ADD_CONTACT_FOR_NOTE_TO_TRUE"
export const SET_ADD_CONTACT_FOR_NOTE_TO_FALSE = "SET_ADD_CONTACT_FOR_NOTE_TO_FALSE"
export const SET_ADG_FAILURE_REASON = "SET_ADG_FAILURE_REASON"
export const SET_ADG_FAILED = "SET_ADG_FAILED"
export const SET_THEME_SELECTED = "SET_CASE_THEME"
export const SET_QUALIFICATION_SELECTED_TRUE = "SET_QUALIFICATION_SELECTED_TRUE"
export const SET_QUALIFICATION_SELECTED_FALSE = "SET_QUALIFICATION_SELECTED_FALSE"
export const SCALING_ELIGIBILITY_LOADING_TRUE = "SCALING_ELIGIBILITY_LOADING_TRUE"
export const SCALING_ELIGIBILITY_LOADING_FALSE = "SCALING_ELIGIBILITY_LOADING_FALSE"
export const SCALING_ELIGIBILITY = "SCALING_ELIGIBILITY"
export const SET_QUALIFICATION_LEAF = "SET_QUALIFICATION_LEAF"
export const SET_DISPLAY_CANCEL_BUTTON = "SET_DISPLAY_CANCEL_BUTTON"
export const SET_ACTIVITY_SELECTED = "SET_ACTIVITY_SELECTED"
export const IS_CURRENT_USER_ELI_TO_AUTOASSIGN = "IS_CURRENT_USER_ELI_TO_AUTOASSIGN"
export const SET_LAST_TRAY_FETCH_DONE = "SET_LAST_TRAY_FETCH_DONE"
export const IS_CURRENT_USER_ELI_TO_UPDATE_CASE = "IS_CURRENT_USER_ELI_TO_UPDATE_CASE"
export const IS_CURRENT_USER_ELI_TO_RE_QUALIFY_CASE = "IS_CURRENT_USER_ELI_TO_REQUALIFY_CASE"
export const IS_CURRENT_USER_OBLIGED_TO_RE_QUALIFY_CASE = "IS_CURRENT_USER_OBLIGED_TO_RE_QUALIFY_CASE"
export const IS_CURRENT_USER_ELI_TO_UPDATE_MANDATORY_ADG_FOR_CASE = "IS_CURRENT_USER_ELI_TO_UPDATE_MANDATORY_ADG_FOR_CASE"
export const IS_CURRENT_USER_ELI_TO_ADD_NOTE_TO_CASE = "IS_CURRENT_USER_ELI_TO_ADD_NOTE_TO_CASE"
export const SET_INCIDENT_SELECTED = "SET_INCIDENT_SELECTED"
export const SET_INCIDENTS_OF_THEME = "SET_INCIDENTS_OF_THEME"
export const SET_UPLOADED_FILES_MAXWELL = "SET_UPLOADED_FILES_MAXWELL"
export const ADD_CONTACT_TRUE = "ADD_CONTACT_TRUE"
export const ADD_CONTACT_FALSE = "ADD_CONTACT_FALSE"
export const SET_BLOCK_ADG_AFTER_SENDING = "SET_BLOCK_ADG_AFTER_SENDING"
export const SET_DISRC_SHOW_UPDATE_CASE = "SET_DISRC_SHOW_UPDATE_CASE"
export const SET_DISABLE_CANCEL_ADG = "SET_DISABLE_CANCEL_ADG"

export const SET_HAS_CALL_TRANSFER = "SET_HAS_CALL_TRANSFER"
export const SET_CALL_TRANSFER_STATUS_OK = "SET_CALL_TRANSFER_STATUS_OK"

export const ADD_FETCHED_CONTACT = "ADD_FETCHED_CONTACT"

// Tray Redux Store Actions Types
export const SYNTHETIC_TRAY_FETCH_CASES_START = "SYNTHETIC_TRAY_FETCH_CASES_START"
export const TRAY_FETCH_CASES_START = "TRAY_FETCH_CASES_START"
export const TRAY_FETCH_CASES_SUCCESS = "TRAY_FETCH_CASES_SUCCESS"
export const TRAY_FETCH_CASES_FAIL = "TRAY_FETCH_CASES_FAIL"

export const TRAY_FETCH_ACTIVITIES_START = "TRAY_FETCH_ACTIVITIES_START"
export const TRAY_FETCH_ACTIVITIES_SUCCESS = "TRAY_FETCH_ACTIVITIES_SUCCESS"
export const TRAY_FETCH_ACTIVITIES_FAIL = "TRAY_FETCH_ACTIVITIES_FAIL"

export const TRAY_FETCH_CASE_AMOUNT_START = "TRAY_FETCH_CASE_AMOUNT_START"
export const TRAY_FETCH_CASE_AMOUNT_SUCCESS = "TRAY_FETCH_CASE_AMOUNT_SUCCESS"
export const TRAY_FETCH_CASE_AMOUNT_FAIL = "TRAY_FETCH_CASE_AMOUNT_FAIL"

export const TRAY_ASSIGN_CASE_START = "TRAY_ASSIGN_CASE_START"
export const TRAY_ASSIGN_CASE_SUCCESS = "TRAY_ASSIGN_CASE_SUCCESS"
export const TRAY_ASSIGN_ACTION_SUCCESS = "TRAY_ASSIGN_ACTION_SUCCESS"
export const TRAY_ASSIGN_CASE_FAIL = "TRAY_ASSIGN_CASE_FAIL"
export const TRAY_ASSIGN_ACTION_FAIL = "TRAY_ASSIGN_ACTION_FAIL"

export const TRAY_AMOUNT_INDICATORS_FETCH_START = "TRAY_AMOUNT_INDICATORS_FETCH_START"
export const TRAY_AMOUNT_INDICATORS_FETCH_SUCCESS = "TRAY_AMOUNT_INDICATORS_FETCH_SUCCESS"
export const TRAY_ACTION_AMOUNT_INDICATORS_FETCH_SUCCESS = "TRAY_ACTION_AMOUNT_INDICATORS_FETCH_SUCCESS"
export const TRAY_ACTION_MONITORING_AMOUNT_INDICATORS_FETCH_SUCCESS = "TRAY_ACTION_MONITORING_AMOUNT_INDICATORS_FETCH_SUCCESS"
export const TRAY_AMOUNT_INDICATORS_FETCH_FAIL = "TRAY_AMOUNT_INDICATORS_FETCH_FAIL"

export const TRAY_ASSIGN_MULTIPLE_CASES_START = "TRAY_ASSIGN_MULTIPLE_CASES_START"
export const TRAY_ASSIGN_MULTIPLE_CASES_SUCCESS = "TRAY_ASSIGN_MULTIPLE_CASES_SUCCESS"
export const TRAY_ASSIGN_MULTIPLE_ACTIONS_SUCCESS = "TRAY_ASSIGN_MULTIPLE_ACTIONS_SUCCESS"
export const TRAY_ASSIGN_MULTIPLE_CASES_FAIL = "TRAY_ASSIGN_MULTIPLE_CASES_FAIL"

export const TRAY_FETCH_SUPERVISOR_CASES_START = "TRAY_FETCH_SUPERVISOR_CASES_START"
export const TRAY_FETCH_SUPERVISOR_CASES_SUCCESS = "TRAY_FETCH_SUPERVISOR_CASES_SUCCESS"
export const TRAY_FETCH_SUPERVISOR_CASES_FAIL = "TRAY_FETCH_SUPERVISOR_CASES_FAIL"

export const TRAY_FETCH_ACTIONS_START = "TRAY_FETCH_ACTIONS_START"
export const TRAY_FETCH_ACTIONS_SUCCESS = "TRAY_FETCH_ACTIONS_SUCCESS"
export const TRAY_FETCH_ACTIONS_FAIL = "TRAY_FETCH_ACTIONS_FAIL"
export const TRAY_FETCH_ACTIONS_AMOUNT_SUCCESS = "TRAY_FETCH_ACTIONS_AMOUNT_SUCCESS"
export const TRAY_EXPORT_ACTIONS_TOGGLE = "TRAY_EXPORT_ACTIONS_TOGGLE"


export const TRAY_UPDATE_PAGINATION = "TRAY_UPDATE_PAGINATION"
export const TRAY_UPDATE_SITE = "TRAY_UPDATE_SITE"

export const STORE_THEMES_SELECTION = "STORE_THEMES_SELECTION"
export const SET_TRAY_HEADER_FILTER = "SET_TRAY_HEADER_FILTER"

// CTI Redux Store Actions Types
export const CTI_FINISHED = "CTI_FINISHED"
export const CTI_ONGOING = "CTI_ONGOING"

export const SET_CASE_MOTIF_LOADING = "SET_CASE_MOTIF_LOADING"
export const SET_QUALIFICATION_WAS_GIVEN_IN_THE_PAYLOAD = "SET_QUALIFICATION_WAS_GIVEN_IN_THE_PAYLOAD"

export const SET_RECENT_CASES = "SET_RECENT_CASES"
export const SET_LOADING_RECENT_CASES = "SET_LOADING_RECENT_CASES"
export const SET_MATCHING_CASE = "SET_MATCHING_CASE"
export const SET_IS_MATCHING_CASE_MODAL_DISPLAYED = "SET_IS_MATCHING_CASE_MODAL_DISPLAYED"
export const SET_IS_LIST_DISPLAYED = "SET_IS_LIST_DISPLAYED"

// ADG Redux Store Action Types
export const ADD_MODIFIED_SERVICE_ID = "ADD_MODIFIED_SERVICE_ID"
export const REMOVE_MODIFIED_SERVICE_ID = "REMOVE_MODIFIED_SERVICE_ID"

// Modals
export const SET_CASE_RESOLUTION_DUNNING_TRUE = "SET_CASE_RESOLUTION_DUNNING_TRUE"
export const SET_CASE_RESOLUTION_DUNNING_FALSE = "SET_CASE_RESOLUTION_DUNNING_FALSE"
export const SHOW_MODAL_CASE_MANAGER = "SHOW_MODAL_CASE_MANAGER"
export const HIDE_MODAL_CASE_MANAGER = "HIDE_MODAL_CASE_MANAGER"
export const TOGGLE_MODAL_CASE_MANAGER = "TOGGLE_MODAL_CASE_MANAGER"
export const MODAL_FORMSY_VALID = "MODAL_FORMSY_VALID"
export const MODAL_FORMSY_INVALID = "MODAL_FORMSY_INVALID"
export const SET_SUCCESS_MODAL_MESSAGE_ID = "SET_SUCCESS_MODAL_MESSAGE_ID"
export const SET_ERROR_MODAL_MESSAGE_ID = "SET_ERROR_MODAL_MESSAGE_ID"
export const SET_ADD_CONTACT_FOR_MODAL = "SET_ADD_CONTACT_FOR_MODAL"


// Maxwell
export const TICKET_CREATING = "TICKET_CREATING"
export const TICKET_OK = "TICKET_OK"
export const TICKET_KO = "TICKET_KO"

export const FILES_UPLOADING = "FILES_UPLOADING"
export const FILES_UPLOADING_OK = "FILES_UPLOADING_OK"
export const FILES_UPLOADING_KO = "FILES_UPLOADING_KO"

export const BEGIN_CREATING_MAXWELL = "BEGIN_CREATING_MAXWELL"
export const BEGIN_CREATING_OK = "BEGIN_CREATING_OK"
export const BEGIN_CREATING_KO = "BEGIN_CREATING_KO"
export const FORM_INCOMPLETE_MAXELL = "FORM_INCOMPLETE_MAXELL"
export const FORM_COMPLETE_MAXELL = "FORM_COMPLETE_MAXELL"


export const OPEN_MAXWELL_MODAL = "OPEN_MAXWELL_MODAL"
export const CLOSE_MAXWELL_MODAL = "CLOSE_MAXWELL_MODAL"

export const SHOW_MODAL_MAXWELL_PROCESS = "SHOW_MODAL_MAXWELL_PROCESS"
export const HIDE_MODAL_MAXWELL_PROCESS = "HIDE_MODAL_MAXWELL_PROCESS"


export const STORE_DIS_RC_ADG_MOTIF = 'STORE_DIS_RC_ADG_MOTIF';
export const STORE_DIS_RC_ID_ACT = 'STORE_DIS_RC_ID_ACT';
export const ALLOW_MAXWELL_MODAL_CLOSING = "ALLOW_MAXWELL_MODAL_CLOSING"
export const DONT_ALLOW_MAXWELL_MODAL_CLOSING = "DONT_ALLOW_MAXWELL_MODAL_CLOSING"

export const SET_INCIDENTS_LIST = "SET_INCIDENTS_LIST";

export const SET_IS_DATE_HERE_FOR_ADG_CTI = "SET_IS_DATE_HERE_FOR_ADG_CTI"
export const RESET_RETENTION_FORM = "RESET_RETENTION_FORM"
export const FETCH_RETENTION_SETTING = "FETCH_RETENTION_SETTING"
export const STORE_RETENTION_SETTING = "STORE_RETENTION_SETTING"
export const STORE_RETENTION_INELIGIBILITY_CAUSES_SETTING = "STORE_RETENTION_INELIGIBILITY_CAUSES_SETTING"
export const STORE_RETENTION_REFUS_SETTING = "STORE_RETENTION_REFUS_SETTING"
export const ERROR_FETCHING_RETENTION_SETTING = "ERROR_FETCHING_RETENTION_SETTING"

export const FETCH_ANTICHURN_SETTING = "FETCH_ANTICHURN_SETTING"
export const STORE_ANTICHURN_SETTING = "STORE_ANTICHURN_SETTING"
export const ERROR_FETCHING_ANTICHURN_SETTING = "ERROR_FETCHING_ANTICHURN_SETTING"

export const FETCH_WEBSAP_SETTINGS = "FETCH_WEBSAP_SETTINGS"
export const STORE_WEBSAP_SETTINGS = "STORE_WEBSAP_SETTINGS"
export const ERROR_FETCHING_WEBSAP_SETTING = "ERROR_FETCHING_WEBSAP_SETTING"
export const FETCH_WEBSAP_ACCESS = "FETCH_WEBSAP_ACCESS"
export const STORE_WEBSAP_ACCESS = "STORE_WEBSAP_ACCESS"
export const ERROR_FETCHING_WEBSAP_ACCESS = "ERROR_FETCHING_WEBSAP_ACCESS"

export const FETCH_BILLINGS_SETTING = "FETCH_BILLINGS_SETTING"
export const STORE_BILLINGS_SETTING = "STORE_BILLINGS_SETTING"
export const ERROR_FETCHING_BILLINGS_SETTING = "ERROR_FETCHING_BILLINGS_SETTING"


// MEDIA
export const FETCH_MEDIA_SETTINGS = "FETCH_MEDIA_SETTINGS"
export const STORE_MEDIA_SETTINGS = "STORE_MEDIA_SETTINGS"
export const ERROR_FETCHING_MEDIA_SETTING = "ERROR_FETCHING_MEDIA_SETTING"

export const SET_USER_ACTIVITY = "SET_USER_ACTIVITY"

// EXTERNAL APPS
export const FETCH_EXTERNAL_APPS = "FETCH_EXTERNAL_APPS"
export const STORE_EXTERNAL_APPS = "STORE_EXTERNAL_APPS"
export const ERROR_FETCHING_EXTERNAL_APPS = "ERROR_FETCHING_EXTERNAL_APPS"
export const FIORI_ACT_OPENED_IN_EXTERNAL_APPS = "FIORI_ACT_OPENED_IN_EXTERNAL_APPS";

// TIME LINE ACTIONS
// REGULARISATIONS
export const SET_TIME_LINE_REGULARISATION = "SET_TIME_LINE_REGULARISATION";
// COMMANDE SEARCH
export const STORE_COMMANDE_SEARCH_FORM = "STORE_COMMANDE_SEARCH_FORM";
export const STORE_COMMANDE_SEARCH_RESULT = "STORE_COMMANDE_SEARCH_RESULT";
export const STORE_COMMANDE_SEARCH_LOADING = "STORE_COMMANDE_SEARCH_LOADING";

// SECURE CALLS
export const STORE_CLIENT_SECURED_CALLS = "STORE_CLIENT_SECURED_CALLS";