export enum TabCategory {
    SYNTHESE = "SYNTHESE",
    HISTORIQUE = "HISTORIQUE",
    ADMINISTRATIVE = "ADMINISTRATIF",
    OFFER_AND_USAGE = "OFFRE & CONSO",
    EQUIPEMENTS = "EQUIPEMENTS",
    BILLS_AND_PAYMENT = "FACTURES ET REGLEMENTS",
    CASES = "CASES"
}
