export enum RetentionProposal {
    OPTION_ENG = "OPTION_ENG",
    ADD_RETREIVE_OPTION = 'ADD_RETREIVE_OPTION',
    MIGRATION = 'MIGRATION',
    ADD_NUMBER = 'ADD_NUMBER',
    RENEWAL = 'RENEWAL',
    TRANSFER = 'TRANSFER',
    ASSIGNEMENT = 'ASSIGNEMENT',
    REGUL = 'REGUL',
    RELOCATION = 'RELOCATION',
    CTI = 'CTI',
    NO_PROPOSAL = 'NO_PROPOSAL',
    CHANGE_OF_CONFORT = 'CHANGE_OF_CONFORT'
}

export enum RetentionProposalWithoutCommitment {
    "PROPOSAL_ACCEPTED" = "PROPOSAL_ACCEPTED",
    "PROPOSAL_REFUSED" = "PROPOSAL_REFUSED",
    "NO_PROPOSAL" = "NO_PROPOSAL"
}

// TODO add other elements of retenttion form