export enum MaxwellProcess {
    PROCESS_LOADING = 'PROCESS LOADING',
    PROCESS_OK = 'PROCESS OK',
    PROCESS_KO = 'PROCESS KO',
    PROCESS_TO_VALIDATE = 'PROCESS TO VALIDATE',
    PROCESS_IGNORED = 'PROCESS_IGNORED',
};
