export default interface HistoriqueDisplay {
  id: number,
  position_createur: string,
  date_realisation: string,
  processing_conclusion: string,
  date_modification: string,
  processing_flag: "Oui" | "Non",
  position: string,
  reference: number,
  comment: string,
  numero: number,
  code_pdv: string,
  assigne_a: string,
  lib_statut: string,
  type_objet: string,
  canal: string,
  createur_login: string,
  activite: string,
  hist_objid: number,
  motif_code: string,
  description: string,
  date_creation: string,
  media_entrant: string,
  motif_adg: string,
  code_adg: string,
  sp_objid: string,
  articles: string,
  prenom_titulaire: string,
  nom_titulaire: string,
  date_anniversaire_titulaire: string,
  offres: string,
  avancement: string,
  civilite_titulaire: string,
  date_cloture: string,
}
