export enum CaseStatus {
    CREATED = 'CREATED',
    RESOLVED = 'RESOLVED',
    CLOSED = 'CLOSED',
    UNRESOLVED = 'UNRESOLVED',
    QUALIFIED = 'QUALIFIED',
    ONGOING = 'ONGOING',
    RESOLVED_REASSIGNED = 'RESOLVED_REASSIGNED'
}