export const STORE_NEW_CONTACT_V2 = "STORE_NEW_CONTACT_V2"
export const STORE_CONTACT_CHANNEL_V2 = "STORE_CONTACT_CHANNEL_V2"
export const STORE_MEDIA_CURRENT_CONTACT = "STORE_MEDIA_TYPE_CONTACT"
export const CONTACT_MEDIA_CHANGED = "CONTACT_MEDIA_CHANGED"
